db:
  image: postgres
  ports:
    - 6542:5432
  environment:
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_DB: test
database_name:
  build: .
  ports:
    - 3001:8080
  links:
    - db
  environment:
    SEQ_DB: test
    SEQ_USER: test
    SEQ_PW: test
    PORT: 8080
    DATABASE_URL: postgres://test:test@db:5432/test
